### ISSUE TITLE
Manual and API 404

### ISSUE THREAD

**Issue by Morabaraba** [qiciengine/qiciengine-documentation#10]
Hi

The links from the main http://www.qiciengine.com/ page for the Manual and API gives a 404 if you follow them. But it seems the manual is still avail via http://docs.qiciengine.com, but I can not find the API.

It would be sad if qici docs lost its Google Ranking because atm I can google "qici behaviour api" to get to the correct page. I'm aware I can run the docs offline, but googling is so much easier.

If you need any assistance in restoring the manual, please let me know.

Thanks,

**Comment by armoonqici** [comment]
fixed

**Comment by Morabaraba** [comment]
Still does not seem to work for me.

```sh
$ curl http://docs.qiciengine.com/manual/index.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /manual/index.html was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at docs-cdn.qiciengine.com Port 80</address>
</body></html>
```

Might it be that the CDN still need to propagate the fix?

**Comment by Morabaraba** [comment]
I tried it again. Still gives a 404 Not Found:

http://docs.qiciengine.com/api
http://docs.qiciengine.com/manual/

as seen in my prev curl output.

Seeing the manual is avail on http://docs.qiciengine.com/, where can I find the API. And won't all the API ancors to the manual broken? 

Edit: For those in search of the docs it is on webarchive, I don't know how complete:

https://web.archive.org/web/20160420055132/http://docs.qiciengine.com/manual/
https://web.archive.org/web/20160417231900/http://docs.qiciengine.com/api/

**Comment by karneaud** [comment]
+1

**Comment by armoonqici** [comment]
try again.
